#ifndef PATHFINDING_GLOBAL_H
#define PATHFINDING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PATHFINDING_LIBRARY)
#  define PATHFINDINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PATHFINDINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PATHFINDING_GLOBAL_H
