#ifndef QUICKPATHER_GLOBAL_H
#define QUICKPATHER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUICKPATHER_LIBRARY)
#  define QUICKPATHERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUICKPATHERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUICKPATHER_GLOBAL_H
